spring:
  application:
    name: eureka-server   # Must match the file name

  config:
    import: configserver:http://localhost:8888
    # Tells this service to fetch configuration from Config Server (port 8888)