server:
  port: 8888

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: git@github.com:cookies042004/Crypto-Config.git
          default-label: main
          clone-on-start: true
          timeout: 20
          ignore-local-ssh-settings: false
          force-pull: true

management:
  endpoints:
    web:
      exposure:
        include: "*"